defmodule Spl.AI.Providers do
  alias Spl.AI.Prompt
  require Logger

  @gemini_url "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
  @openrouter_url "https://openrouter.ai/api/v1/chat/completions"

  def call(:gemini, params) do
    api_key = System.get_env("GEMINI_API_KEY")

    if is_nil(api_key) do
      {:error, :missing_api_key}
    else
      prompt = Prompt.build(params)

      body = %{
        contents: [%{parts: [%{text: prompt}]}],
        generationConfig: %{temperature: 0.7, maxOutputTokens: 1024}
      }

      url = "#{@gemini_url}?key=#{api_key}"

      case Req.post(url,
             json: body,
             receive_timeout: 30_000,
             connect_options: [timeout: 10_000]
           ) do
        {:ok, %{status: 200, body: body}} ->
          case parse_gemini_response(body) do
            {:ok, draft} ->
              Logger.info("✅ AI draft generated by: gemini-1.5-flash")
              {:ok, draft}

            error ->
              error
          end

        {:ok, %{status: 429}} ->
          {:error, :rate_limited}

        {:ok, %{status: status, body: body}} ->
          Logger.error("Gemini HTTP error #{status}: #{inspect(body)}")
          {:error, {:http_error, status}}

        {:error, reason} ->
          Logger.error("Gemini request failed: #{inspect(reason)}")
          {:error, reason}
      end
    end
  end

  def call(:openrouter_free, params) do
    call_openrouter(params, "z-ai/glm-4.5-air:free")
  end

  def call(:openrouter_fallback, params) do
    call_openrouter(params, "nvidia/nemotron-nano-9b-v2:free")
  end

  def call(:openrouter_gemma, params) do
    call_openrouter_gemma(params, "google/gemma-4-26b-a4b-it:free")
  end

  defp call_openrouter(params, model) do
    allowed_origin = System.get_env("ALLOWED_ORIGINS")
    Logger.info("ALLOWED_ORIGINS present? #{!is_nil(allowed_origin)}")
    api_key = System.get_env("OPENROUTER_API_KEY")
    Logger.info("OPENROUTER_API_KEY present? #{!is_nil(api_key)}")
    prompt = Prompt.build(params)

    body = %{
      model: model,
      messages: [
        %{role: "system", content: Prompt.system_prompt()},
        %{role: "user", content: prompt}
      ],
      max_tokens: 1024,
      temperature: 0.7
    }

    headers = [
      {"Authorization", "Bearer #{api_key}"},
      {"HTTP-Referer", "#{allowed_origin}"},
      {"X-Title", "Esanpol"}
    ]

    case Req.post(@openrouter_url,
           json: body,
           headers: headers,
           receive_timeout: 15_000,
           connect_options: [timeout: 5_000]
         ) do
      {:ok, %{status: 200, body: body}} ->
        case parse_openrouter_response(body) do
          {:ok, draft} ->
            Logger.info("✅ AI draft generated by: #{model}")
            {:ok, draft}

          error ->
            error
        end

      {:ok, %{status: 429}} ->
        {:error, :rate_limited}

      {:ok, %{status: status, body: body}} ->
        Logger.error("OpenRouter HTTP error #{status}: #{inspect(body)}")
        {:error, {:http_error, status}}

      {:error, reason} ->
        Logger.error("OpenRouter request failed: #{inspect(reason)}")
        {:error, reason}
    end
  end

  defp call_openrouter_gemma(params, model) do
    api_key = System.get_env("OPENROUTER_API_KEY")
    allowed_origin = System.get_env("ALLOWED_ORIGINS")

    combined_prompt = """
    #{Prompt.system_prompt()}

    ---

    #{Prompt.build(params)}
    """

    body = %{
      model: model,
      messages: [
        %{role: "user", content: combined_prompt}
      ],
      max_tokens: 1024,
      temperature: 0.7
    }

    headers = [
      {"Authorization", "Bearer #{api_key}"},
      {"HTTP-Referer", "#{allowed_origin}"},
      {"X-Title", "Esanpol"}
    ]

    case Req.post(@openrouter_url,
           json: body,
           headers: headers,
           receive_timeout: 15_000,
           connect_options: [timeout: 5_000]
         ) do
      {:ok, %{status: 200, body: body}} ->
        case parse_openrouter_response(body) do
          {:ok, draft} ->
            Logger.info("✅ AI draft generated by: #{model}")
            {:ok, draft}

          error ->
            error
        end

      {:ok, %{status: 429}} ->
        {:error, :rate_limited}

      {:ok, %{status: status, body: body}} ->
        Logger.error("Gemma HTTP error #{status}: #{inspect(body)}")
        {:error, {:http_error, status}}

      {:error, reason} ->
        Logger.error("Gemma request failed: #{inspect(reason)}")
        {:error, reason}
    end
  end

  defp parse_gemini_response(%{
         "candidates" => [%{"content" => %{"parts" => [%{"text" => text}]}} | _]
       }) do
    parse_draft_text(text)
  end

  defp parse_gemini_response(_), do: {:error, :invalid_response}

  defp parse_openrouter_response(%{"choices" => [%{"message" => %{"content" => text}} | _]}) do
    parse_draft_text(text)
  end

  defp parse_openrouter_response(_), do: {:error, :invalid_response}

  defp parse_draft_text(text) do
    clean =
      text
      |> String.trim()
      |> String.replace(~r/```json\s*/i, "")
      |> String.replace(~r/```\s*/, "")
      |> String.trim()

    with {:error, _} <- try_json_decode(clean),
         {:ok, extracted} <- extract_json_object(clean),
         {:ok, result} <- try_json_decode(extracted) do
      {:ok, result}
    else
      {:ok, result} ->
        {:ok, result}

      _ ->
        Logger.warning("Could not parse AI response as JSON, returning raw text")
        {:ok, %{subject: "", body: clean}}
    end
  end

  defp try_json_decode(text) do
    case Jason.decode(text) do
      {:ok, %{"subject" => subject, "body" => body}} ->
        {:ok, %{subject: subject, body: body}}

      _ ->
        {:error, :invalid_json}
    end
  end

  defp extract_json_object(text) do
    case Regex.run(~r/\{[\s\S]*\}/u, text) do
      [match] -> {:ok, match}
      _ -> {:error, :no_json_found}
    end
  end
end
