import Config

# db_username = System.get_env("DB_USERNAME")
# db_password = System.get_env("DB_PASSWORD")
# db_name = System.get_env("DB_NAME")
# db_host = System.get_env("DB_HOSTNAME")

# # Configure your database
# config :triggerflow, Triggerflow.Repo,
#   username:  db_username,
#   password:  db_password,
#   database:  db_name,
#   hostname:  db_host,
#   port: 3306,
#   connect_opts: [allowPublicKeyRetrieval: true, ssl: false],
#   pool_size: 10,
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :spl, SplWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "pR1NF8Rz9D2DSXY721VxCiIOjLkswjanqAMzmUHcoCXwuBY+qDf+Fbv+At52ARHD",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :spl, dev_routes: true

# Do not include metadata nor timestamps in development logs
# config :logger, :default_formatter, format: "[$level] $message\n"

config :logger, level: :debug
config :logger, backends: [:console]

config :logger, :console,
  format: "[$level] $message\n",
  metadata: [:request_id, :module, :function]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
